#version 450 

layout (local_size_x = 256) in;

layout(set = 0, binding = 0) uniform Config{
    vec3 thisPos;
    int posCount;
} opData;

layout(set = 0, binding = 1) readonly buffer InputBuffer{
    vec3 pos[];
} sourceData;

layout(set = 0, binding = 2) buffer OutputBuffer{
    vec3 pos[];
} outputData;

void main() {
	uint gID = gl_GlobalInvocationID.x;

    if(gID < opData.posCount)
    {
        outputData.pos[gID] = sourceData.pos[gID] * opData.thisPos;
    }
}